site_name: Visión por Computador
use_directory_urls: false

theme:
  name: material
  features:
    - content.code.copy
    - content.tooltips

nav:
- Instalación de OpenCV : 'install.md'
- T1- Introducción : 'intro.md'
- T2- Imagen digital y vídeo : 'imagenvideo.md'
#- T3- Transformaciones : 'transformaciones.md'
#- T4- Detección : 'deteccion.md'
#- T5- Segmentación : 'segmentacion.md'
#- T6- Características : 'caracteristicas.md'
#- T7- Reconocimiento : 'reconocimiento.md'

theme:
    language: es
    name: 'material'
    palette:
        primary: 'Teal'
        accent: 'Teal'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    features:
        - content.code.copy
#    logo: 'imagenes/logo.png'

# Ponemos como idioma de búsqueda el inglés
# para conseguir que busque correctamente
# todas las palabras en castellano, sin eliminar
# los excesivos derivados que se definen en 
# https://github.com/MihaiValentin/lunr-languages/blob/master/lunr.es.js

extra:
    search:
        language: 'en'
        
# Problema: pdf-export solo admite que las imagenes de la pagina sean pdf o svg, no otros formatos
#plugins:
#    - pdf-export

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - mdx_math
  - codehilite:
      linenums: false
  - footnotes
  - meta
  - sane_lists
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
 
plugins:
  - search
